<?php

namespace OpcacheBundle\Repository;

/**
 * OpCacheDataModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpCacheDataModelRepository extends \Doctrine\ORM\EntityRepository
{
}
